import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
const inter = Inter( { subsets: [ "latin" ] } );
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Sidebar from "@/components/Sidebar";
import {ReduxProvider} from "@/app/redux/provider";

export const metadata: Metadata = {
  title: "Montage India",
  description: "Generated by create next app",
};

export default function RootLayout ( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> )
{
  return (
    <html lang="en">
      <body className={ inter.className }>
      <ToastContainer />
        <ReduxProvider>        
        {/* <div className="flex  ">
        <div className="w-20"> <Sidebar/></div>
       <div >{ children }</div>
       </div> */}

          <Sidebar />
          { children }
        </ReduxProvider>
      </body>
    </html>
  );
}