import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
const inter = Inter( { subsets: [ "latin" ] } );
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Montage India",
  description: "Generated by create next app",
};

export default function RootLayout ( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> )
{
  return (
    <html lang="en">
      <body className={ inter.className }>
        <ToastContainer />
        <div className="flex">
          <Sidebar />
          <main className="flex-1 ml-20"> 
            { children }
          </main>
        </div>
      </body>
    </html>
  );
}