version: "3.6"
services:
  nginx:
    ports:
      - "8000:80"
  mi-server:
    build:
      context: .
      args:
        NODE_ENV: development
    env_file:
      - ./.env    
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
