version: "3.6"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  mi-server:
    build: .
    image: image/mi-server
    env_file:
      - ./.env
