version: "3.6"
services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped  
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ms4544311@gmail.com -d thequantumhive.site --agree-tos    
  mi-server:
    build:
      context: .
      args:
        NODE_ENV: poduction
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env   
    command: npm start
