version: "3.6"
services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/thequantumhive.site/fullchain.pem:/etc/nginx/ssl/nginx.crt
      - /etc/letsencrypt/live/thequantumhive.site/privkey.pem:/etc/nginx/ssl/nginx.key
      
  mi-server:
    build:
      context: .
      args:
        NODE_ENV: poduction
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env   
    command: npm start
