export const metadata = {
  title: 'Montage India',
  description: 'Generated by Next.js',
}
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

// import "../globals.css";
import { ReduxProvider } from "../redux/provider";

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <div>
      <ReduxProvider>        
      <ToastContainer />
      {children}
      </ReduxProvider>        
      </div>
  )
}
