export const metadata = {
  title: 'Montage India',
  description: 'Generated by Next.js',
}
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

import "../globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <ToastContainer />
      {children}</body>
    </html>
  )
}
